# Лимиты на уровне nginx
limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;
limit_req_zone $binary_remote_addr zone=api:10m rate=100r/m;
limit_req_zone $binary_remote_addr zone=static:10m rate=1000r/m;

# Лимиты на соединения
limit_conn_zone $binary_remote_addr zone=addr:10m;

events {
    worker_connections 10000;
    multi_accept on;
    use epoll;
}

http {
    # Ослабляем таймауты для теста
    keepalive_timeout 120;
    keepalive_requests 10000;
    client_header_timeout 120;
    client_body_timeout 120;
    send_timeout 120;
    
    upstream backend {
        server backend:3000;
        keepalive 512;
    }
}

server {
	listen 80 default_server;
	access_log  /var/log/nginx/access.log;
	error_log  /var/log/nginx/error.log debug;
    client_max_body_size 10m;

    # Общие лимиты
    limit_conn addr 10;  # максимум 10 соединений с одного IP
    client_body_timeout 5s;
    client_header_timeout 5s;
    
    # Защита от медленных запросов
    client_body_buffer_size 1k;
    client_header_buffer_size 1k;
    client_max_body_size 1m;
    large_client_header_buffers 2 1k;

    location /api/ {
        rewrite ^/api(.*)$ $1  break;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~* \.(json|ico)$ {
        root /var/public/;
        try_files $uri $uri/ =404;
    }

    location / {
        root /var/app;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}