- name: Проверка nginx
  run: |
    docker exec $(docker ps -q -f name=nginx) nginx -t
    docker exec $(docker ps -q -f name=nginx) curl http://localhost

- name: Запуск контейнеров
  run: |
    docker-compose down
    docker-compose up -d
    echo "Ожидание 30 секунд..."
    sleep 30
    docker-compose ps
    curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost